### PR TITLE
Apply separate weights for unet and text encoder

### PR DESCRIPTION
**Pull request by Naegles**
This Pull Request makes it possible to apply separate weights to the unet and text encoder, which allows for finer adjustments after training. This should be pretty useful since training both the unet and tenc perfectly is pretty hard.

I tested that the resulting images with tenc_weight == unet_weight are equal to the resulting images from before this change with the same weight.

### CODE REVIEW

**Comment by kohya-ss** [comment]
Thank you for this!

The code has changed significantly due to merging other PRs. And it would be possible to write a script to change the LoRA weights with different values for U-Net and Text Encoder in advance. I wonder it might be a good way to keep the extension simple.

**Comment by sashasubbbb** [comment]
This is extremely helpful, would like to see it merged. Thank you.

**Comment by space-nuko** [comment]
Thanks for this, just a heads-up I implemented the XY grid support and this change will require some updates to that code so it doesn't break. It's because the XY grid support depends on how many arguments are available to the `process` method

https://github.com/kohya-ss/sd-webui-additional-networks/blob/5abd8b0aedf5f282b2ebff4f43006c5cfec3fde0/scripts/additional_networks.py#L340

And the infotext restoration code too, it needs to handle backwards compatibility when the two weights were served by a single parameter and support for the new infotext parameter. It might need some scrutiny

https://github.com/kohya-ss/sd-webui-additional-networks/blob/5abd8b0aedf5f282b2ebff4f43006c5cfec3fde0/scripts/additional_networks.py#L434

I would like to see this merged too, would be cool to tinker around with

**Comment by kohya-ss** [comment]
Implemented with #72. Thank you for the idea!

**Pull request closed without merging**
