### PR TITLE
XY grid support

### PR DESCRIPTION
**Pull request by space-nuko**
NOTE: This requires #21 first

Support for weight/model parameters in XY grid.

### CODE REVIEW

**Review by kohya-ss — COMMENTED** [review]
Thank you for PR again!
I think "Get comma-separated list of models (for XY Grid)" in "Additional Networks" tab gives a input value for "AddNet Model X" in X/Y plot.
However, the value from "Get comma..." includes the model hash in the model name, but "AddNet Model X" assumes that the value is the list of the model name without the hash.
I manually edit the value, the X/Y plot works well.

In addition, when I push "Get List" button in "Additional Network" tab leaving the "Model" text box as "None", it gives "file not found: None" for "Model list".

I understand that the metadata is used in X/Y plot. It's great!

**Comment by space-nuko** [comment]
I fixed it so either the name with hash or just the model name works. It's possible there could be two models with the same name, that's why I wanted the XY grid to support including the hash

Also since https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/6685 was merged I fixed another issue where the infotext could not be restored if there was already an additional_networks model in a slot where there was no infotext parameter

**Comment by kohya-ss** [comment]
Thank you! 
The X/Y grid works with and without the model hash. The update for the infotext is also good!

I have a plan to add another network such as Hypernetwork or Custom Diffusion, I think it will need to be modified then, but that is probably possible. 

I have one question that I hope you can answer if you don't mind.
If we add the another weight, the current one as U-Net weight and the additional one as Text Encoder weight, can we simply add a new parameter like ``AddNet Weight2``? (and modify magic number ``3`` to ``4``.)

**Comment by space-nuko** [comment]
> I have one question that I hope you can answer if you don't mind.
If we add the another weight, the current one as U-Net weight and the additional one as Text Encoder weight, can we simply add a new parameter like AddNet Weight2? (and modify magic number 3 to 4.)

Yeah that's how it should work. The parameter modifying is based on the index of the argument to the `process` function. I think that's the best that can be done with the current script API

**Comment by space-nuko** [comment]
And thanks a ton for all your work

**Comment by kohya-ss** [comment]
Thank you for your answer. So it is not too hard (but it is somewhat complicated.) 

Thank you too for the great code!

**Pull request merged**
